### ISSUE TITLE
jQuery is not loaded on site

### ISSUE THREAD

**Issue by Lorentzen1337** [rAutoChess/rAutoChess.github.io#4]
It seems that the cdn you have chosen for jQuery is not up and running anymore:
`<script src="https://code.pxdn.cloud/jquery/1.11.1/jquery-1.11.1.min.js"></script>` 

Resulting in the typical error:

> $ is not defined

You should consider transfering to another or include it on the site directly.

**Comment by kyoto-shift** [comment]
Awesome thanks for letting me know. I just updated it
